services:
  jobmanager:
    image: flink:1.20
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  #        restart-strategy: fixed-delay
  #        restart-strategy.fixed-delay.attempts: 100
  #        restart-strategy.fixed-delay.delay: 0 s
  taskmanager:
    image: flink:1.20
    container_name: taskmanager
    depends_on:
      - jobmanager
      - redis
      - kafka
      - mongo
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
  #        restart-strategy: fixed-delay
  #        restart-strategy.fixed-delay.attempts: 100
  #        restart-strategy.fixed-delay.delay: 0 s

  redis:
    image: redis/redis-stack:7.4.0-v2
    ports:
      - "6379:6379"
      - "8001:8001"

  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - "9092:9092"

  mongo:
    image: mongo:8.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: passwordm

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8082:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwordm
      ME_CONFIG_MONGODB_URL: mongodb://mongo:passwordm@mongo:27017/
      ME_CONFIG_BASICAUTH: false